### ISSUE TITLE
runtime error, ubuntu 18.04-LTS

### ISSUE THREAD

**Issue by strusty** [kerneis/babelweb#7]
sysadmin@gopi:/opt/babelweb/bin$ ./babelweb 
   info  - socket.io started
/opt/babelweb/node_modules/policyfile/lib/server.js:254
Object.keys(process.EventEmitter.prototype).forEach(function proxy (key){
                                 ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/opt/babelweb/node_modules/policyfile/lib/server.js:254:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/babelweb/node_modules/policyfile/index.js:1:80)
    at Module._compile (module.js:652:30)
sysadmin@gopi:/opt/babelweb/bin$ npm start -g babelweb

> babelweb@0.4.0 start /opt/babelweb
> ./bin/babelweb "babelweb"

Warning: couldn't parse option babelweb
   info  - socket.io started
/opt/babelweb/node_modules/policyfile/lib/server.js:254
Object.keys(process.EventEmitter.prototype).forEach(function proxy (key){
                                 ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/opt/babelweb/node_modules/policyfile/lib/server.js:254:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/babelweb/node_modules/policyfile/index.js:1:80)
    at Module._compile (module.js:652:30)

npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "-g" "babelweb"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! babelweb@0.4.0 start: `./bin/babelweb "babelweb"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babelweb@0.4.0 start script './bin/babelweb "babelweb"'.
npm ERR! **Make sure you have the latest version of node.js and npm installed.**
npm ERR! If you do, this is most likely a problem with the babelweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/babelweb "babelweb"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs babelweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls babelweb
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "-g" "babelweb"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.449859375
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

**Comment by kerneis** [comment]
Hi, babelweb is not maintained anymore. Could you please try https://github.com/Vivena/babelweb2 instead, which should be supported and offer the same functionality, and email babel-users@ if it doesn't work?

Thanks,
Gabriel
